### ISSUE TITLE
Could you please upload your config files?

### ISSUE THREAD

**Issue by Simbaclaws** [Metamist/dotfiles#1]
Hi,

I want to copy some of your dotfiles.
Could you please upload some of your files that are currently symlinks?
After copying over the dot files my i3 config is now empty :(

**Comment by Metamist** [comment]
My config files are already there. I am using a program that I developed that lets me switch between different themes and templates for my config files.
Rather than looking for them where they should be, look in `.config/metaswitcher/templates` or `.config/metaswitcher/themes`
